spring:
  datasource:
    url: jdbc:mysql://${JEEBBS_DB_HOST}/jeebbs
    username: ${JEEBBS_DB_USER}
    password: ${JEEBBS_DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update

server:
  address: ${JEEBBS_SERVER_ADDRESS:0.0.0.0}
  port: ${JEEBBS_SERVER_PORT:8080}

logging:
  level:
    root: info
  path: ${JEEBBS_LOG_PATH:/var/log/jeebbs}
  file:
    max-history: ${JEEBBS_LOG_MAX_HISTORY:10}
    max-size: ${JEEBBS_LOG_MAX_SIZE:10MB}

jeebbs:
  quartz:
    news:
      cron: "0 0/10 6-23 * * ?"